version: 2.1
executors:
  deploy_container:
    docker:
      - image: circleci/python:3.9.0
    working_directory: ~/work

orbs:
  aws-cli: circleci/aws-cli@1.3.2
  slack: circleci/slack@3.4.2

jobs:
  flake8_lint:
    executor: deploy_container
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install flake8
      - run:
          name: Lint with flake8
          command: |
            flake8 --count --select=F --show-source --statistics
  notify-approval:
    executor: deploy_container
    steps:
      - slack/approval:
          message: "本番環境へのデプロイを承認してください"
          mentions: "here"
          color: "#F5E911"
          webhook: ${SLACK_WEBHOOK}

workflows:
  server_flake8_test:
    jobs:
      - flake8_lint
